version: "3.8"

services:
  worldwise-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: worldwise-app:latest
    container_name: worldwise-app
    restart: unless-stopped

networks:
  default:
    name: npm_default
    external: true
