version: "3.8"

services:
  worldwise-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: worldwise-app
    restart: unless-stopped
    depends_on:
      - worldwise-api

  worldwise-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: worldwise-api
    restart: unless-stopped

networks:
  default:
    name: npm_default
    external: true
